### PR TITLE
Removed strange control characters from study.txt

### PR DESCRIPTION
**Pull request by dominikl**
Just removed the weird control characters from the study txt. I still have to save it as UTF-8, maybe that's why github still doesn't display it as plain text file.

/cc @francesw

### CODE REVIEW

**Comment by joshmoore** [comment]
GitHub says: "Binary file not shown."  😱

**Comment by dominikl** [comment]
Weird, isn't it? Any idea how to fix that?

**Comment by joshmoore** [comment]
```

$ file idr0061-study.txt
idr0061-study.txt: Algol 68 source text, Little-endian UTF-16 Unicode text, with very long lines, with CRLF, CR, LF line terminators
```
Screen Shot 2019-07-02 at 22 31 00
Beeindrückend

**Comment by joshmoore** [comment]
I tried pushing a copy of the file and saw this:
Screen Shot 2019-07-02 at 22 47 27
My guess is that after this PR is merged, it will display normally.

**Comment by dominikl** [comment]
I thought I removed all these weird characters. Hm, I'll try again.

**Pull request merged**
